fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: [--style=file, -i]
  - repo: https://github.com/sbrunner/hooks
    rev: faef5fb92013a6a60087a0d9f962a90fb898e8c5
    hooks:
      - id: copyright
        name: update-copyright-line
        args: [--config=.copyright-updater-config.yaml, --required]
        types_or: ["c++", "cmake", "xml"]
