fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: [--style=file, -i]
  - repo: https://github.com/nanoufo/copyright-hook
    rev: 54d4dab
    hooks:
      - id: update-copyright
        name: update-copyright
        args: [--required]
        types_or: ["c++", "cmake"]
 